name: example
on:
  schedule:
    - cron: '*/1 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210230
          schedule-id: 100002
          seat-id: 1_0
          slack-incoming-webhook-url: https://hooks.slack.com/services/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
          message: '<@U12345678> 달려달려~'
